name: build_covid_cghr_dev
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_covid_cghr_dev:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout covid-data
      uses: actions/checkout@v2
      with:
        path: main
    - name: Checkout covid.cghr.dev
      uses: actions/checkout@v2
      with:
        repository: cghr-toronto/covid.cghr.dev
        ssh-key: ${{ secrets.SSH_KEY }}
        path: website
    - name: Pull covid-data submodule
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - name: Install snap
      run: | 
        sudo apt update
        sudo apt install snapd
    - name: Install hugo
      run: |
        sudo snap install hugo
    - name: Build website with hugo
      run: hugo --minify
