name: build_covid_cghr_dev
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_covid_cghr_dev:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone covid.cghr.dev
      run: |
        git clone https://github.com/cghr-toronto/covid.cghr.dev
        cd covid.cghr.dev
    - name: Pull covid-data submodule
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - name: Install snap
      run: | 
        sudo apt update
        sudo apt install snapd
    - name: Install hugo
      run: |
        sudo snap install hugo
    - name: Build website with hugo
      run: hugo --minify
